### ISSUE TITLE
compliance with BioC2020 requirements

### ISSUE THREAD

**Issue by lwaldron** [LihuaJulieZhu/CRISPRseekGUIDEseqBioc2020Workshop#1]
I think there are still a couple issues here preventing building a Docker image and pkgdown site, which is due by July 16 to remain on the BioC2020 program. Please reach out for extra help if you need it on the #biocworkshopbook Slack channel on bioc-community. We can probably find extra help for you too if you need it.

**Comment by mdozmorov** [comment]
[Instructions](https://github.com/seandavi/BuildABiocWorkshop2020/blob/master/vignettes/HOWTO_BUILD_WORKSHOP.Rmd)

**Comment by mdozmorov** [comment]
@jianhong, @LihuaJulieZhu, the URL in your DESCRIPTION file is malformatted.

**Comment by lwaldron** [comment]
URL was fixed in 6f3e931765bc5eafaeeb4ba6227180164ed743bb. I think everything looks OK now.

**Comment by mdozmorov** [comment]
Yes, all pieces are in place, the issue can be closed
